USE erp_ws;
GO
DELETE FROM dbo.CPP_PROVEEDOR_CLIENTE
GO
DELETE FROM dbo.CPP_CONTACTO
GO
DELETE FROM dbo.CPP_GRUPO
GO
DELETE FROM dbo.CPP_CONCEPTO
GO
DELETE FROM dbo.CPP_PROVEEDOR_CLIENTE_CONCEPTO
GO
DELETE FROM dbo.CPP_EVENTO_CONCEPTO
GO
DELETE FROM dbo.CPP_FACTURA
GO
DELETE FROM dbo.CPC_BANCO
GO
DELETE FROM dbo.CPP_FORMA_PAGO_COBRO
GO
DELETE FROM dbo.CPC_SUCURSAL
GO
DELETE FROM dbo.CPC_TIPO_CAMBIO
GO
DELETE FROM dbo.CPC_CONTRATO
GO
DELETE FROM dbo.CPC_PAGO_CONTRATO
GO
DELETE FROM dbo.CPC_ITEM
GO
DELETE FROM dbo.CPC_CONTRATO_ITEM
GO
DELETE FROM dbo.CPC_DOSIFICACION
GO
DELETE FROM dbo.CPC_FACTURA_EMITIDA
GO
DELETE FROM dbo.CPC_DETALLE_FACTURA
GO
DELETE FROM dbo.CPC_PAGO
GO
DELETE FROM dbo.DOCUMENTO_PAGO
GO
DELETE FROM dbo.par_valor
GO
DELETE FROM dbo.PAR_ACTIVIDAD_ECONOMICA
GO
DELETE FROM dbo.PAR_BANCO
GO
DELETE FROM dbo.PAR_CARACTERISTICA_ESPECIAL
GO
DELETE FROM dbo.PAR_DEPARTAMENTO
GO
DELETE FROM dbo.PAR_ESTADO
GO
DELETE FROM dbo.PAR_ESTADO_FACTURA
GO
DELETE FROM dbo.PAR_ESTADO_PAGO
GO
DELETE FROM dbo.PAR_ESTADO_PROCESO
GO
DELETE FROM dbo.PAR_FORMA_DE_PAGO
GO
DELETE FROM dbo.PAR_LOCALIZACION
GO
DELETE FROM dbo.PAR_MES
GO
DELETE FROM dbo.PAR_MODALIDAD_FACTURACION
GO
DELETE FROM dbo.PAR_MODALIDAD_TRANSACCION
GO
DELETE FROM dbo.PAR_MUNICIPIO
GO
DELETE FROM dbo.PAR_PERIODO
GO
DELETE FROM dbo.PAR_RECURRENCIA
GO
DELETE FROM dbo.PAR_TIPO_CONTACTO
GO
DELETE FROM dbo.PAR_TIPO_DOCUMENTO
GO
DELETE FROM dbo.PAR_TIPO_DOCUMENTO_MERCANTIL
GO
DELETE FROM dbo.PAR_TIPO_DOCUMENTO_PAGO
GO
DELETE FROM dbo.PAR_TIPO_GRUPO
GO
DELETE FROM dbo.PAR_TIPO_ITEM
GO
DELETE FROM dbo.PAR_TIPO_MONEDA
GO
DELETE FROM dbo.PAR_TIPO_PAGO
GO
DELETE FROM dbo.PAR_TIPO_PROVEEDOR_CLIENTE
GO
DELETE FROM dbo.PAR_TIPO_REGISTRO
GO
DELETE FROM dbo.PAR_TIPO_RETENCION
GO
DELETE FROM dbo.PAR_TIPO_TRANSACCION
GO