USE cpanel;
GO
DELETE FROM dbo.ADM_PERSONA
GO
DELETE FROM dbo.ADM_USUARIO
GO
DELETE FROM dbo.ADM_PERFIL
GO
DELETE FROM dbo.ADM_SESSION
GO
DELETE FROM dbo.ADM_ROL
GO
DELETE FROM dbo.ADM_USUARIO_ROL
GO
DELETE FROM dbo.ADM_PERMISO
GO
DELETE FROM dbo.ADM_MODULO
GO
DELETE FROM dbo.CLI_EMPRESA
GO
DELETE FROM dbo.CLI_MODULO_EMPRESA
GO
DELETE FROM dbo.PAR_VALOR
GO
DELETE FROM dbo.par_estado_permiso
GO
DELETE FROM dbo.par_estado_usuario
GO
DELETE FROM dbo.par_tipo
GO
DELETE FROM dbo.par_tipo_documento
GO